fruitipedia_app/fruitipedia_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("fruitipedia_app.common.urls")),
    path("fruit/", include("fruitipedia_app.fruit.urls")),
    path("profile/", include("fruitipedia_app.user_profile.urls")),

]

fruitipedia_app/fruitipedia_app/user_profile/urls.py
from django.urls import path

from fruitipedia_app.user_profile.views import ProfileCreateView, ProfileEditView, ProfileDetailsView, ProfileDeleteView

urlpatterns = (
    path('create/', ProfileCreateView.as_view(), name='profile-create'),
    path('details/', ProfileDetailsView.as_view(), name='profile-details'),
    path('edit/', ProfileEditView.as_view(), name='profile-edit'),
    path('delete/', ProfileDeleteView.as_view(), name='profile-delete'),
)

fruitipedia_app/fruitipedia_app/fruit/models.py
from django.core.validators import MinLengthValidator
from django.db import models

from fruitipedia_app.fruit.validators import fruit_name_validator
from fruitipedia_app.user_profile.models import Profile


# Create your models here.
class Fruit(models.Model):
    name = models.CharField(
        unique=True,
        max_length=30,
        validators=[MinLengthValidator(2), fruit_name_validator],
        error_messages={"unique": "This fruit name is already in use! Try a new one."}
    )

    image_url = models.URLField()

    description = models.TextField()

    nutrition = models.TextField(
        null=True,
        blank=True,
    )

    owner = models.ForeignKey(
        Profile,
        on_delete=models.CASCADE,
        blank=True,
    )

fruitipedia_app/fruitipedia_app/user_profile/models.py
from django.core.validators import MinLengthValidator
from django.db import models

from fruitipedia_app.user_profile.validators import profile_name_validator, profile_password_validator


# Create your models here.
class Profile(models.Model):
    first_name = models.CharField(
        max_length=25,
        validators=[
            MinLengthValidator(2),
            profile_name_validator,
        ])

    last_name = models.CharField(
        max_length=35,
        validators=[
            MinLengthValidator(1),
            profile_name_validator,
        ])

    email = models.EmailField(
        max_length=40,
        unique=True,
    )

    password = models.CharField(
        max_length=20,
        validators=[profile_password_validator],
    )

    image_url = models.URLField(
        null=True,
        blank=True,
    )

    age = models.IntegerField(
        null=False,
        blank=True,
        default=18,
    )

fruitipedia_app/fruitipedia_app/user_profile/forms.py
from django import forms

from fruitipedia_app.user_profile.models import Profile


class ProfileBaseForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ("first_name", "last_name", "email", "password")
        widgets = {
            "first_name": forms.TextInput(attrs={'placeholder': "First Name"}),
            "last_name": forms.TextInput(attrs={'placeholder': "Last Name"}),
            "email": forms.EmailInput(attrs={'placeholder': "Email"}),
            "password": forms.PasswordInput(attrs={'placeholder': "Password"}),
        }


class ProfileCreateForm(ProfileBaseForm):
    class Meta(ProfileBaseForm.Meta):
        labels = {
            "first_name": "",
            "last_name": "",
            "email": "",
            "password": "",
        }
        help_texts = {"password": "*Password length requirements: 8 to 20 characters"}


class ProfileDetailsForm(ProfileBaseForm):
    pass


class ProfileEditForm(ProfileBaseForm):
    class Meta(ProfileBaseForm.Meta):
        fields = ("first_name", "last_name", "image_url", "age")
        labels = {
            "first_name": "First Name",
            "last_name": "Last Name",
            "image_url": "Image URL",
        }


class ProfileDeleteForm(ProfileBaseForm):
    pass

fruitipedia_app/fruitipedia_app/user_profile/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic as views

from fruitipedia_app.user_profile.forms import ProfileCreateForm, ProfileEditForm
from fruitipedia_app.user_profile.models import Profile


# Create your views here.
class ProfileGetMixin:
    def get_object(self, queryset=None):
        return Profile.objects.first()


class ProfileCreateView(views.CreateView):
    form_class = ProfileCreateForm
    queryset = Profile.objects.all()
    template_name = "user_profile/create-profile.html"
    success_url = reverse_lazy("dashboard")


class ProfileDetailsView(views.DetailView):
    template_name = "user_profile/details-profile.html"

    def get_object(self, queryset=None):
        return Profile.objects.first()


class ProfileEditView(ProfileGetMixin, views.UpdateView):
    form_class = ProfileEditForm
    queryset = Profile.objects.all()
    template_name = "user_profile/edit-profile.html"
    success_url = reverse_lazy("profile-details")


class ProfileDeleteView(ProfileGetMixin, views.DeleteView):
    template_name = "user_profile/delete-profile.html"
    success_url = reverse_lazy("index")

fruitipedia_app/templates/user_profile/create-profile.html
{% extends 'base.html' %}
{% block main_content %}

    <main>
        <!-- Create Profile Form -->
        <section id="register">
            <div class="form">
                <h2>Create Profile</h2>
                <form action="{% url 'profile-create' %}" class="register-form" method="post">
                    {{ form }}
{#                    <input#}
{#                            type="text"#}
{#                            name="first-name"#}
{#                            id="first-name"#}
{#                            placeholder="First Name"#}
{#                    />#}
{#                    <input#}
{#                            type="text"#}
{#                            name="last-name"#}
{#                            id="last-name"#}
{#                            placeholder="Last Name"#}
{#                    />#}
{#                    <input#}
{#                            type="email"#}
{#                            name="email"#}
{#                            id="register-email"#}
{#                            placeholder="Email"#}
{#                    />#}
{#                    <div class="helptext" id="id_password_helptext">#}
{#                        *Password length requirements: 8 to 20 characters#}
{#                    </div>#}
{#                    <input#}
{#                            type="password"#}
{#                            name="password"#}
{#                            id="register-password"#}
{#                            placeholder="Password"#}
{#                    />#}

                    <button type="submit">Create</button>
                    {% csrf_token %}
                </form>
            </div>
        </section>
    </main>
{% endblock %}

fruitipedia_app/templates/user_profile/delete-profile.html
{% extends 'base.html' %}
{% block main_content %}

    <main>

        <section id="edit">

            <div class="form">
                <h1>Are you sure you want to delete your profile?</h1>

                <!-- Delete Profile Form -->
                <form action="{% url 'profile-delete' %}" id='delete' class="register-form" method="post">
                    <!-- Confirm Button -->
                    <button type="submit">Yes</button>
                    {% csrf_token %}
                </form>
                <!-- End Delete Profile Form -->
            </div>

        </section>
    </main>
{% endblock %}

fruitipedia_app/templates/user_profile/details-profile.html
{% extends 'base.html' %}
{% load static %}
{% block main_content %}

    <main>

        <!-- Profile Details Section -->

        <section id="details">
            <div id="details-wrapper">
                <h2>Profile Details</h2>
                {% if object.image_url %}
                    <!-- if the user has a profile image -->
                    <img id="details-img" src="{{ object.image_url }}"
                         alt="profile img"/>
                {% else %}
                    <!-- if the user has NO profile image -->
                    <img id="details-img" src="{% static 'images/default.jpg' %}" alt="profile img"/>
                {% endif %}
                <!-- user's full name -->
                <p id="details-title">{{ object.first_name }} {{ object.last_name }}</p>

                <div id="info-wrapper">
                    <div id="details-description">
                        <!-- email -->
                        <p>
                            {{ object.email }}
                        </p>
                        <!-- age -->
                        <p>
                            {{ object.age }}
                        </p>
                        <!-- number of posts -->
                        <p id="nutrition">Posts: {{ object.fruit_set.count }}</p>

                    </div>

                    <!--Edit and Delete buttons -->
                    <div id="action-buttons">
                        <a href="{% url 'profile-edit' %}" id="edit-btn">Edit</a>
                        <a href="{% url 'profile-delete' %}" id="delete-btn">Delete</a>
                    </div>
                </div>
            </div>
        </section>

    </main>
{% endblock %}

fruitipedia_app/templates/user_profile/edit-profile.html
{% extends 'base.html' %}
{% block main_content %}

    <main>

        <!-- Edit Profile Form -->

        <section id="register">
            <div class="form">
                <h2>Edit Profile</h2>
                <form action="{% url 'profile-edit' %}" class="register-form" method="post">
                    {{ form }}
                    {#                    <label for="first-name">First Name:</label>#}
                    {#                    <input#}
                    {#                            type="text"#}
                    {#                            name="first name"#}
                    {#                            id="first-name"#}
                    {#                            value="Mariya"#}
                    {#                    />#}
                    {#                    <label for="last-name">Last Name:</label>#}
                    {#                    <input#}
                    {#                            type="text"#}
                    {#                            name="last name"#}
                    {#                            id="last-name"#}
                    {#                            value="Petrova"#}
                    {#                    />#}
                    {#                    <label for="url">Image URL:</label>#}
                    {#                    <input#}
                    {#                            type="url"#}
                    {#                            name="url"#}
                    {#                            id="url"#}
                    {#                            value="https://images.pexels.com/photos/3792581/pexels-photo-3792581.jpeg"#}
                    {#                    />#}
                    {#                    <label for="age">Age:</label>#}
                    {#                    <input#}
                    {#                            type="number"#}
                    {#                            name="age"#}
                    {#                            id="age"#}
                    {#                            value="18"#}
                    {#                    />#}
                    <button type="submit">Edit</button>
                    {% csrf_token %}
                </form>
            </div>
        </section>

    </main>
{% endblock %}